POST http://127.0.0.1:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMyIsImlkIjoiNjU3MmYyMjU2Zjg0YTFmZmRiM2Q4MTViIiwiaWF0IjoxNzA1Njg4NzE3LCJleHAiOjE3MDU2OTIzMTd9.jcbpNKW42VWcwLyqXSPZUAstxpAsUTuJlKUd3yo9yNw

{
    "title": "Sample Blog 11d",
    "author": "John Doe",
    "url": "http://some.address.com",
    "likes": 15

}