POST http://127.0.0.1:3003/api/comments/65aabf00cb3500b5a3f636d4
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMyIsImlkIjoiNjU3MmYyMjU2Zjg0YTFmZmRiM2Q4MTViIiwiaWF0IjoxNzA1Njg4NzE3LCJleHAiOjE3MDU2OTIzMTd9.jcbpNKW42VWcwLyqXSPZUAstxpAsUTuJlKUd3yo9yNw

{
    "comment": "Sample comment",
    "date": "1970-01-01T00:00:00.000Z"
}